server:
  port: 8080
  servlet:
    context-path: /bird_sys
  tomcat:
    max-http-form-post-size: -1


spring:
  datasource:
    name: bird_sys
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/im_bird?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    filters: stat
    initial-size: 2 # 初始化连接
    max-idle: 10 # 最大空闲连接数
    min-idle: 1 # 最小空闲连接数
    max-wait: 60000
    max-active: 20 # 最大活动连接数
    # 间隔多久进行一次检测，检测需要关闭的空闲连接
    time-between-evict-runs-millis: 60000
    #一个连接在池中最小的存活时间
    min-evictable-time-millis: 300000
    # 验证连接有效与否的SQL， 不同的数据配置不同
    validation-query: SELECT 'x'
    # 指明连接是否被空闲连接回收器（如果有）进行验证，如果检测失败，则连接从池中去除。
    test-while-idle: true
    # 借出连接时不要测试， 否则影响性能。
    test-on-borrow: false
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.1.15:22122

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl